export const LOAD__TEMPLATES_SUCCESS = 'LOAD__TEMPLATES_SUCCESS';
export const UPDATE__TEMPLATE_SUCCESS = 'UPDATE__TEMPLATE_SUCCESS';
export const CREATE__TEMPLATE_SUCCESS = 'CREATE__TEMPLATE_SUCCESS';
export const DELETE__TEMPLATE_SUCCESS = 'DELETE__TEMPLATE_SUCCESS';
export const UPSERT__TEMPLATE_SUCCESS = 'UPSERT__TEMPLATE_SUCCESS';

export const LOAD_ITEMTYPES_SUCCESS = 'LOAD_ITEMTYPES_SUCCESS';
export const UPDATE_ITEMTYPE_SUCCESS = 'UPDATE_ITEMTYPE_SUCCESS';
export const CREATE_ITEMTYPE_SUCCESS = 'CREATE_ITEMTYPE_SUCCESS';
export const DELETE_ITEMTYPE_SUCCESS = 'DELETE_ITEMTYPE_SUCCESS';
export const UPSERT_ITEMTYPE_SUCCESS = 'UPSERT_ITEMTYPE_SUCCESS';

export const LOAD_PICKLISTS_SUCCESS = 'LOAD_PICKLISTS_SUCCESS';
export const UPDATE_PICKLIST_SUCCESS = 'UPDATE_PICKLIST_SUCCESS';
export const CREATE_PICKLIST_SUCCESS = 'CREATE_PICKLIST_SUCCESS';
export const DELETE_PICKLIST_SUCCESS = 'DELETE_PICKLIST_SUCCESS';
export const UPSERT_PICKLIST_SUCCESS = 'UPSERT_PICKLIST_SUCCESS';

export const LOAD_PROFICIENCIES_SUCCESS = 'LOAD_PROFICIENCIES_SUCCESS';
export const UPDATE_PROFICIENCY_SUCCESS = 'UPDATE_PROFICIENCY_SUCCESS';
export const CREATE_PROFICIENCY_SUCCESS = 'CREATE_PROFICIENCY_SUCCESS';
export const DELETE_PROFICIENCY_SUCCESS = 'DELETE_PROFICIENCY_SUCCESS';
export const UPSERT_PROFICIENCY_SUCCESS = 'UPSERT_PROFICIENCY_SUCCESS';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';