export const LOAD__TEMPLATES_SUCCESS = 'LOAD__TEMPLATES_SUCCESS';
export const UPDATE__TEMPLATE_SUCCESS = 'UPDATE__TEMPLATE_SUCCESS';
export const CREATE__TEMPLATE_SUCCESS = 'CREATE__TEMPLATE_SUCCESS';
export const DELETE__TEMPLATE_SUCCESS = 'DELETE__TEMPLATE_SUCCESS';
export const UPSERT__TEMPLATE_SUCCESS = 'UPSERT__TEMPLATE_SUCCESS';

export const LOAD_BACKGROUNDS_SUCCESS = 'LOAD_BACKGROUNDS_SUCCESS';
export const UPDATE_BACKGROUND_SUCCESS = 'UPDATE_BACKGROUND_SUCCESS';
export const CREATE_BACKGROUND_SUCCESS = 'CREATE_BACKGROUND_SUCCESS';
export const DELETE_BACKGROUND_SUCCESS = 'DELETE_BACKGROUND_SUCCESS';
export const UPSERT_BACKGROUND_SUCCESS = 'UPSERT_BACKGROUND_SUCCESS';

export const LOAD_EQUIPMENTS_SUCCESS = 'LOAD_EQUIPMENTS_SUCCESS';
export const UPDATE_EQUIPMENT_SUCCESS = 'UPDATE_EQUIPMENT_SUCCESS';
export const CREATE_EQUIPMENT_SUCCESS = 'CREATE_EQUIPMENT_SUCCESS';
export const DELETE_EQUIPMENT_SUCCESS = 'DELETE_EQUIPMENT_SUCCESS';
export const UPSERT_EQUIPMENT_SUCCESS = 'UPSERT_EQUIPMENT_SUCCESS';

export const LOAD_ITEMTYPES_SUCCESS = 'LOAD_ITEMTYPES_SUCCESS';
export const UPDATE_ITEMTYPE_SUCCESS = 'UPDATE_ITEMTYPE_SUCCESS';
export const CREATE_ITEMTYPE_SUCCESS = 'CREATE_ITEMTYPE_SUCCESS';
export const DELETE_ITEMTYPE_SUCCESS = 'DELETE_ITEMTYPE_SUCCESS';
export const UPSERT_ITEMTYPE_SUCCESS = 'UPSERT_ITEMTYPE_SUCCESS';

export const LOAD_PICKLISTS_SUCCESS = 'LOAD_PICKLISTS_SUCCESS';
export const UPDATE_PICKLIST_SUCCESS = 'UPDATE_PICKLIST_SUCCESS';
export const CREATE_PICKLIST_SUCCESS = 'CREATE_PICKLIST_SUCCESS';
export const DELETE_PICKLIST_SUCCESS = 'DELETE_PICKLIST_SUCCESS';
export const UPSERT_PICKLIST_SUCCESS = 'UPSERT_PICKLIST_SUCCESS';
export const UPDATE_PICKLIST_ITEM_SUCCESS = 'UPDATE_PICKLIST_ITEM_SUCCESS';

export const LOAD_PROFICIENCIES_SUCCESS = 'LOAD_PROFICIENCIES_SUCCESS';
export const UPDATE_PROFICIENCY_SUCCESS = 'UPDATE_PROFICIENCY_SUCCESS';
export const CREATE_PROFICIENCY_SUCCESS = 'CREATE_PROFICIENCY_SUCCESS';
export const DELETE_PROFICIENCY_SUCCESS = 'DELETE_PROFICIENCY_SUCCESS';
export const UPSERT_PROFICIENCY_SUCCESS = 'UPSERT_PROFICIENCY_SUCCESS';

export const LOAD_SPELLS_SUCCESS = 'LOAD_SPELLS_SUCCESS';
export const UPDATE_SPELL_SUCCESS = 'UPDATE_SPELL_SUCCESS';
export const CREATE_SPELL_SUCCESS = 'CREATE_SPELL_SUCCESS';
export const DELETE_SPELL_SUCCESS = 'DELETE_SPELL_SUCCESS';
export const UPSERT_SPELL_SUCCESS = 'UPSERT_SPELL_SUCCESS';

export const LOAD_SPELLLISTS_SUCCESS = 'LOAD_SPELLLISTS_SUCCESS';
export const UPDATE_SPELLLIST_SUCCESS = 'UPDATE_SPELLLIST_SUCCESS';
export const CREATE_SPELLLIST_SUCCESS = 'CREATE_SPELLLIST_SUCCESS';
export const DELETE_SPELLLIST_SUCCESS = 'DELETE_SPELLLIST_SUCCESS';
export const UPSERT_SPELLLIST_SUCCESS = 'UPSERT_SPELLLIST_SUCCESS';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';